config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#index"


  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers, :gallery
    end
  end

  resources :posts,          only: [:create, :destroy, :update]
  resources :relationships,  only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ul class="posts">
    <%= render @feed_items %>
  </ul>
<% end %>

app/views/shared/_login_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :remember_me do %>
        <%= f.check_box :remember_me %>
        <span>Remember me on this computer</span>
      <% end %>

      <%= f.submit "Log in" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", new_user_path %></p>
  </div>
</div>

app/views/shared/_post_form.html.erb
<%= form_for(@post, html: { multipart: true }) do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Write your message here",
                              class: 'form-control' %>
  </div>
  <div class="image-desc">
    <%= f.text_field :image_desc, placeholder: "Image description",
                                 class: 'form-control' %>
  </div>
  <div class="media">
    <%= f.text_field :media, placeholder: "Insert youtube link here",
                             class: 'form-control' %>
  </div>
  <span class="picture">
    <%= f.file_field :image, accept: 'image/jpeg,image/gif,image/png',
                             class: 'form-control' %>
  </span>
  <%= f.submit "Create post", class: "btn btn-primary" %>
<% end %>