config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#index"


  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers, :gallery
    end
  end

  resources :posts,          only: [:create, :destroy, :update]
  resources :relationships,  only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  before_save { self.media = media.split("=").last }
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :content, presence: true, length: {maximum: 200}
  validates :user_id, presence: true
  mount_uploader :image, AvatarUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:succes] = "Post created"
      redirect_to root_url
    else
      @post_items = []
      flash[:warning] = "Post invalid"
      redirect_to root_url
    end
  end

  def destroy
    @post.destroy
    redirect_to root_url
  end

  private

  def post_params
    params.require(:post).permit(:content, :image, :image_desc, :media)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <% if post.user.avatar.present? %>
    <span class="avatar"><%= link_to image_tag(post.user.avatar.url, size: "50"), user_path(post.user) %></span>
  <% end %>
  <strong class="username"><%= full_name(post.user) %></strong>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user?(post.user) %>
      <%= link_to "delete", post, method: :delete, class: "right" %>
    <% end %>
  </span>
  <span class="content"><%= post.content %></span>
  <span class="post-image"><%= image_tag post.image if post.image %></span>
  <% unless post.media.blank? %>
    <span class="youtube-player">
      <iframe width="560" height="349" src="http://www.youtube.com/embed/<%= post.media %>"
       frameborder="0"></iframe>
    </span>
  <% end %>
</li>

app/views/posts/_posts.html.erb
<li id="post-<%= post.id %>">
  <%= link_to post.user.avatar.url, users_path(post.user) =>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>