config/routes.rb
Rails.application.routes.draw do
  
  root "static_pages#index"


  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users do
    member do
      get :following, :followers, :gallery
    end
  end

  resources :posts,          only: [:create, :destroy, :update]
  resources :relationships,  only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_aside.html.erb
<% @user ||= current_user %>

<section class="user_info">
  <%= link_to @user do %>
    <h1><%= full_name @user %></h1>
  <% end %>
  <%= image_tag @user.avatar.url(:avatar) unless @user.avatar.blank? %>
  <br>
  <% if current_user?(@user) %>
    <%= link_to "Edit profile", edit_user_path(current_user), class: "btn btn-default" %>
  <% else %>
    <%= render "follow_form" if logged_in? %>  
  <% end %>
</section>

<section class="friends">
  <% @user.followers.order("RANDOM()").limit(8).each do |follower| %>
    <%= link_to follower do %>
      <%= image_tag follower.avatar.url, size: "50", alt: full_name(follower) %>
    <% end %>
  <% end %>
  <br>
  <a href="<%= followers_user_path(@user) %>" class="btn btn-default">
    All <%= @user.followers.count %> followers
  </a>
</section>

<section class="gallery">
  <% @user.gallery.order("RANDOM()").limit(8).each do |post| %>
    <%= image_tag post.image.url, height: "50" %>
  <% end %>
  <br>
  <a href="<%= gallery_user_path(@user) %>" class="btn btn-default">
    Gallery
  </a>
</section>

app/views/layouts/_navbar.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "CACTUS", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Show profile", current_user %></li>
              <li><%= link_to "Edit profile", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>